export enum EEnvKey {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    GLOBAL_PREFIX = 'GLOBAL_PREFIX',
    SWAGGER_PATH = 'SWAGGER_PATH',
    CACHE_TTL = 'CACHE_TTL',

    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_USERNAME = 'DB_USERNAME',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_DATABASE = 'DB_DATABASE',

    JWT_SECRET_KEY = 'JWT_SECRET_KEY',
    JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET_KEY',
    JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
    JWT_REFRESH_EXPIRATION_TIME = 'JWT_REFRESH_EXPIRATION_TIME',
}
